# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [1]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def sigmoid(x, div=False):
    if div == True:
        return sigmoid(x) * (1-sigmoid(x))
    return 1/(1+np.exp(-x))

X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
        
# define y for output dataset            
Y = np.array([[0, 0, 1, 1]]).T

In [2]:
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
## (b-a)*np.random.random((row, column)) + (a) : (row, column):建立矩陣大小 , 隨機取值範圍[a, b)
w_layer1 = 2*np.random.random((3, 2)) - 1  # a=-1 b=1 , 第1層weights取值介於 -1~1
w_layer2 = 2*np.random.random((2, 1)) - 1
iter = 0

神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [3]:
for iter in range(10000):
    # forward propagation
    z1 = X.dot(w_layer1)
    a1 = sigmoid(z1)
    z2 = a1.dot(w_layer2)
    a2 = sigmoid(z2)
    
    # how much did we miss?
    loss = (-2)*Y + 2*a2
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    delta_z2 = loss*sigmoid(z2, div=True)
    delta_a1 = delta_z2.dot(w_layer2.T)
    delta_z1 = delta_a1*sigmoid(z1, div=True)
        
    # update weights
    w_layer1 -= X.T.dot(delta_z1)
    w_layer2 -= a1.T.dot(delta_z2)
    # syn1 update weights
    
print("Output After Training:")
print(f'a1 : \n {a1}\n')
print(f'a2 : \n {a2}\n')
print(f'Real Y:\n {Y}')

Output After Training:
a1 : 
 [[0.89571489 0.12108664]
 [0.90203803 0.09952268]
 [0.05927686 0.94162877]
 [0.06327816 0.92827099]]

a2 : 
 [[0.00408339]
 [0.00340512]
 [0.9963642 ]
 [0.99592884]]

Real Y:
 [[0]
 [0]
 [1]
 [1]]
